use hospital_management;


-- Most Consulted Doctors

SELECT d.name , COUNT(a.appointment_id) AS total_appointments
FROM doctors d JOIN appointments a ON d.doctor_id = a.doctor_id
GROUP BY d.name 
ORDER BY total_appointments DESC;

-- ----------------------------------------------------------------------------------------

-- Total Revenue Per Month

SELECT date_format(date,'%Y-%m') AS month , SUM(cost) as total_revenue
FROM treatments
GROUP BY month
ORDER BY month;

-- ----------------------------------------------------------------------------------------

-- Most Common Diseases

SELECT diagnosis , COUNT(*) AS frequency 
FROM treatments
GROUP BY diagnosis
ORDER BY frequency DESC;


-- -----------------------------------------------------------------------------------------

-- Patient Visit Frequency

SELECT p.name ,count(a.appointment_id) AS visit_count
FROM patients p JOIN appointments a ON p.patient_id = a.patient_id
GROUP BY p.name
ORDER BY visit_count DESC;

-- ------------------------------------------------------------------------------------------

-- Doctor Performance Analysis

SELECT d.name , count(a.appointment_id) AS total_patients , avg(t.cost) AS avg_treatment_cost
FROM doctors d
JOIN appointments a ON d.doctor_id = a.doctor_id
JOIN treatments t ON a.patient_id = t.patient_id
GROUP BY d.name
ORDER BY total_patients DESC;

-- --------------------------------------------------------------------------------------------

-- Top Earning Doctor

SELECT d.name , sum(t.cost) AS total_revenue
FROM doctors d JOIN appointments a ON d.doctor_id = a.doctor_id
JOIN treatments t ON a.patient_id = t.patient_id
GROUP BY d.name
ORDER BY total_revenue DESC
LIMIT 1;

-- --------------------------------------------------------------------------------------------

-- Patients with Highest Spending

SELECT p.name, sum(t.cost) AS total_spent
FROM patients p
JOIN treatments t ON p.patient_id = t.patient_id
GROUP BY p.name
ORDER BY total_spent DESC;


-- ------------------------------------------------------------------------------------------

-- Disease-wise Total Revenue

SELECT diagnosis , SUM(cost) AS total_revenue
FROM treatments
GROUP BY diagnosis
ORDER BY total_revenue DESC;


-- ------------------------------------------------------------------------------------------

-- Total Patients per doctor

SELECT d.name AS doctor_name , COUNT(DISTINCT a.patient_id) AS total_patients
FROM doctors d
JOIN appointments a ON d.doctor_id = a.doctor_id
GROUP BY d.name
ORDER BY total_patients DESC;


-- ------------------------------------------------------------------------------------------

-- Average Treatment Cost Per Disease

SELECT diagnosis , AVG(cost) AS avg_cost
FROM treatments
GROUP BY diagnosis
ORDER BY avg_cost DESC;

-- -----------------------------------------------------------------------------------------

-- Doctor Specialization Count

SELECT specialization , COUNT(*) AS total_doctors
FROM doctors
GROUP BY specialization; 


-- -----------------------------------------------------------------------------------------

-- Daily Revenue Report

SELECT date , SUM(cost) AS daily_revenue
FROM treatments
GROUP BY date
ORDER BY date;


-- ----------------------------------------------------------------------------------------

-- Monthly Patient Count

SELECT date_format(date,'%Y-%m') AS month , count(distinct patient_id) AS total_patient
FROM Appointments
GROUP BY month
ORDER BY month; 


-- -----------------------------------------------------------------------------------------

-- Revenue Generated By Each Doctor

SELECT  d.name , SUM(t.cost) AS total_revenue
FROM Doctors d
JOIN Appointments a ON d.doctor_id = a.doctor_id
JOIN Treatments t ON a.patient_id = t.patient_id
GROUP BY d.name
ORDER BY total_revenue DESC;



